// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7_bRuoj86tY4mg9RHMF4bf0hW6K_4xas',
    appId: '1:768841240655:web:388188aa799f75a1a95a3a',
    messagingSenderId: '768841240655',
    projectId: 'flutterprojectapplication',
    authDomain: 'flutterprojectapplication.firebaseapp.com',
    storageBucket: 'flutterprojectapplication.appspot.com',
    measurementId: 'G-L1361SBGEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkpGB4Z7rT7SGNShL-H8AIXpwSdRBQLYg',
    appId: '1:768841240655:android:ccda0acdce73574fa95a3a',
    messagingSenderId: '768841240655',
    projectId: 'flutterprojectapplication',
    storageBucket: 'flutterprojectapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLYJHsloJeoV0dMg8VYj7Z7k0U3dgG8Yk',
    appId: '1:768841240655:ios:63155ddbae185696a95a3a',
    messagingSenderId: '768841240655',
    projectId: 'flutterprojectapplication',
    storageBucket: 'flutterprojectapplication.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLYJHsloJeoV0dMg8VYj7Z7k0U3dgG8Yk',
    appId: '1:768841240655:ios:3e4527490e9d08f7a95a3a',
    messagingSenderId: '768841240655',
    projectId: 'flutterprojectapplication',
    storageBucket: 'flutterprojectapplication.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
